"""initial schema

Revision ID: c656a9850ad6
Revises: 
Create Date: 2026-09-27 13:57:54.328705
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = 'c656a9850ad6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Schemas + extension the SDD's modular monolith relies on. Must run
    # before any table below that uses schema=... or a vector column.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    for _schema in ("audio", "content", "corpus", "analytics"):
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {_schema}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name', 'version')
    )
    op.create_table('lecture_audio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('opus_path', sa.String(length=500), nullable=False),
    sa.Column('aac_path', sa.String(length=500), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('voice', sa.String(length=64), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='audio'
    )
    op.create_index(op.f('ix_audio_lecture_audio_cache_key'), 'lecture_audio', ['cache_key'], unique=True, schema='audio')
    op.create_table('question_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name_ko', sa.String(length=120), nullable=False),
    sa.Column('name_vi', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='content'
    )
    op.create_table('corpus_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('film_id', sa.String(length=64), nullable=False),
    sa.Column('text_ko', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('register', sa.String(length=32), nullable=False),
    sa.Column('topic_ids', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='corpus'
    )
    op.execute(
        "CREATE INDEX ix_corpus_item_embedding_hnsw ON corpus.corpus_item "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute(
        "CREATE INDEX ix_corpus_item_topic_ids_gin ON corpus.corpus_item "
        "USING gin (topic_ids)"
    )
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('learner', 'editor', 'admin', name='profile_role'), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('goal', sa.Enum('talk', 'topik1', 'topik4', 'topik5', 'topik6', name='profile_goal'), nullable=True),
    sa.Column('exam_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.create_table('learning_event',
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('skill', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('learner_id', 'occurred_at', 'event_id'),
    schema='analytics',
    postgresql_partition_by='RANGE (occurred_at)'
    )
    # Default catch-all partition so inserts never fail for a month with
    # no dedicated partition yet. Add real monthly partitions
    # (FOR VALUES FROM ... TO ...) via a scheduled job or a later migration
    # once the analytics module is actually wired up.
    op.execute(
        "CREATE TABLE analytics.learning_event_default "
        "PARTITION OF analytics.learning_event DEFAULT"
    )
    op.create_table('exam_paper',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_kind', sa.String(length=32), nullable=False),
    sa.Column('session_label', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('answer_status', sa.String(length=32), nullable=False),
    sa.Column('import_job_id', sa.UUID(), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'file_hash', name='uq_exam_paper_owner_hash'),
    schema='content'
    )
    op.create_table('error_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('skill', sa.String(length=32), nullable=False),
    sa.Column('error_type', sa.String(length=64), nullable=False),
    sa.Column('example_ko', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batch',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('lesson', 'corpus', 'exam_paper', name='import_kind'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'extracting', 'validating', 'awaiting_review', 'confirmed', 'cancelled', 'rolled_back', 'failed', name='import_batch_status'), nullable=False),
    sa.Column('flagged_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='job_status'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('step', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'idempotency_key', name='uq_job_type_idempotency')
    )
    op.create_index(op.f('ix_jobs_idempotency_key'), 'jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('vocab_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('term_ko', sa.String(length=120), nullable=False),
    sa.Column('meaning_vi', sa.String(length=255), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writing_submission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'image_rejected', 'transcribing', 'awaiting_confirmation', 'grading', 'graded', 'revising', 'revised', 'rewriting', name='writing_submission_status'), nullable=False),
    sa.Column('image_key', sa.String(length=500), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_passage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('body_ko', sa.Text(), nullable=True),
    sa.Column('chart_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_key', sa.String(length=500), nullable=True),
    sa.Column('audio_key', sa.String(length=500), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=False),
    sa.Column('source_bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['content.exam_paper.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='content'
    )
    op.create_table('import_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'flagged_yellow', 'flagged_red', 'confirmed', 'rejected', name='import_item_status'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('vocab_item_id', sa.UUID(), nullable=False),
    sa.Column('srs_stage', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ease', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['learner_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['vocab_item_id'], ['vocab_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'vocab_item_id', name='uq_item_state_learner_item')
    )
    op.create_table('writing_score',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score_min', sa.Integer(), nullable=False),
    sa.Column('score_max', sa.Integer(), nullable=False),
    sa.Column('priority_fixes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('score_min <= score_max', name='ck_writing_score_range'),
    sa.ForeignKeyConstraint(['submission_id'], ['writing_submission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('passage_id', sa.UUID(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('qtype_id', sa.UUID(), nullable=False),
    sa.Column('stem_ko', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', sa.SmallInteger(), nullable=True),
    sa.Column('answer_source', sa.Enum('editor', 'ai_guess', name='exam_item_answer_source'), nullable=True),
    sa.Column('difficulty_est', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('import_item_id', sa.UUID(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['content.exam_paper.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['passage_id'], ['content.exam_passage.id'], ),
    sa.ForeignKeyConstraint(['qtype_id'], ['content.question_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'number', name='uq_exam_item_paper_number'),
    schema='content'
    )
    op.create_table('exam_item_tag',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('tag_kind', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['content.exam_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'tag_kind', 'ref_id'),
    schema='content'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_item_tag', schema='content')
    op.drop_table('exam_item', schema='content')
    op.drop_table('writing_score')
    op.drop_table('item_state')
    op.drop_table('import_item')
    op.drop_table('exam_passage', schema='content')
    op.drop_table('writing_submission')
    op.drop_table('vocab_item')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_idempotency_key'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('import_batch')
    op.drop_table('error_log')
    op.drop_table('exam_paper', schema='content')
    op.execute("DROP TABLE IF EXISTS analytics.learning_event_default")
    op.drop_table('learning_event', schema='analytics')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_table('corpus_item', schema='corpus')
    op.drop_table('question_type', schema='content')
    op.drop_index(op.f('ix_audio_lecture_audio_cache_key'), table_name='lecture_audio', schema='audio')
    op.drop_table('lecture_audio', schema='audio')
    op.drop_table('app_config')
    # ### end Alembic commands ###
    # SQLAlchemy's sa.Enum() creates a standalone Postgres TYPE per table
    # that isn't dropped along with the table — must be dropped explicitly
    # or the next `upgrade head` fails with DuplicateObject.
    for _enum in (
        "profile_role",
        "profile_goal",
        "job_status",
        "import_kind",
        "import_batch_status",
        "writing_submission_status",
        "import_item_status",
        "exam_item_answer_source",
    ):
        op.execute(f"DROP TYPE IF EXISTS {_enum}")
    for _schema in ("audio", "content", "corpus", "analytics"):
        op.execute(f"DROP SCHEMA IF EXISTS {_schema} CASCADE")
